services:
  app:
    build: .
    restart: unless-stopped
    command: ['npm', 'run', 'start:dev']
    environment:
      PORT: ${PORT:-3333} # Sets the default to 3333 if it doesn't exist
    networks:
      - app-tier
    ports:
      - '3333:3333'
    depends_on:
      - db
      # db:
      # condition: service_healthy
    working_dir: /app
    volumes:
      - ./:/app

  db:
    image: bitnami/postgresql:latest
    restart: unless-stopped
    environment:
      POSTGRESQL_USERNAME: friedrich-pg
      POSTGRESQL_PASSWORD: friedrich-pw
      POSTGRESQL_DATABASE: friedrich-db
    volumes:
      - db-data:/bitnami/postgresql
    networks:
      - app-tier
    ports:
      - '5432:5432'
    # expose:
    #   - '5432'
    # healthcheck:
    #   test: ['CMD-SHELL', 'pg_isready']
    # interval: 10s
    # timeout: 5s
    # retries: 5

volumes:
  db-data:

networks:
  app-tier:
    driver: bridge
