

services:
  friedrich-pg:
    image: "bitnami/postgresql:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=friedrich-pg
      - POSTGRESQL_PASSWORD=friedrich-pw
      - POSTGRESQL_DATABASE=friedrich-db